import React, { useEffect, useState } from 'react';
import {
  Box,
  Typography,
  Button,
  Paper,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Alert,
  CircularProgress,
  Chip,
  Card,
  CardContent,
  Divider,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
} from '@mui/material';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import BarChartIcon from '@mui/icons-material/BarChart';
import ShowChartIcon from '@mui/icons-material/ShowChart';
import PieChartIcon from '@mui/icons-material/PieChart';
import SpeedIcon from '@mui/icons-material/Speed';
import GridOnIcon from '@mui/icons-material/GridOn';
import SendIcon from '@mui/icons-material/Send';
import CheckIcon from '@mui/icons-material/Check';
import SettingsIcon from '@mui/icons-material/Settings';
import { useAppStore } from '../../store';
import {
  getAiConfig,
  suggestDashboard,
  createReport,
} from '../../services/api';
import type {
  SuggestedWidget,
  AiConfig,
  WidgetLayout,
} from '../../services/api';

const WIDGET_ICONS: Record<string, React.ReactNode> = {
  bar: <BarChartIcon />,
  line: <ShowChartIcon />,
  pie: <PieChartIcon />,
  kpi: <SpeedIcon />,
  table: <GridOnIcon />,
};

const WIDGET_DEFAULTS: Record<string, { w: number; h: number }> = {
  table: { w: 6, h: 4 },
  bar: { w: 6, h: 4 },
  line: { w: 6, h: 4 },
  pie: { w: 4, h: 4 },
  kpi: { w: 3, h: 2 },
};

export default function AIAssistant() {
  const queries = useAppStore((s) => s.queries);
  const fetchQueries = useAppStore((s) => s.fetchQueries);
  const fetchReports = useAppStore((s) => s.fetchReports);
  const setActiveTab = useAppStore((s) => s.setActiveTab);

  const [selectedQueryId, setSelectedQueryId] = useState<number | ''>('');
  const [aiConfig, setAiConfig] = useState<AiConfig | null>(null);
  const [loading, setLoading] = useState(false);
  const [suggestions, setSuggestions] = useState<SuggestedWidget[] | null>(null);
  const [sampleInfo, setSampleInfo] = useState<{ columns: number; rows: number } | null>(null);
  const [message, setMessage] = useState<{ type: 'success' | 'error' | 'info'; text: string } | null>(null);
  const [applying, setApplying] = useState(false);

  useEffect(() => {
    fetchQueries();
    getAiConfig().then(setAiConfig).catch(() => {});
  }, [fetchQueries]);

  const handleGenerate = async () => {
    if (!selectedQueryId) return;
    setLoading(true);
    setSuggestions(null);
    setSampleInfo(null);
    setMessage(null);

    try {
      const result = await suggestDashboard(selectedQueryId as number);
      setSuggestions(result.widgets);
      setSampleInfo({ columns: result.columns.length, rows: result.sampleRowCount });
      if (result.widgets.length === 0) {
        setMessage({ type: 'info', text: 'AI did not return any widget suggestions. Try a different query.' });
      }
    } catch (err: any) {
      setMessage({ type: 'error', text: err.response?.data?.error || err.message || 'AI generation failed' });
    } finally {
      setLoading(false);
    }
  };

  const handleApplyToCanvas = async () => {
    if (!suggestions || suggestions.length === 0 || !selectedQueryId) return;
    setApplying(true);

    try {
      // Build widget layout from suggestions
      const layout: WidgetLayout[] = [];
      let currentX = 0;
      let currentY = 0;

      for (let i = 0; i < suggestions.length; i++) {
        const s = suggestions[i];
        const defaults = WIDGET_DEFAULTS[s.type] || { w: 6, h: 4 };

        // Wrap to next row if needed
        if (currentX + defaults.w > 12) {
          currentX = 0;
          currentY += 4;
        }

        layout.push({
          i: `ai-widget-${Date.now()}-${i}`,
          x: currentX,
          y: currentY,
          w: defaults.w,
          h: defaults.h,
          type: s.type as WidgetLayout['type'],
          config: {
            title: s.title,
            queryId: selectedQueryId as number,
            xAxis: s.xAxis || undefined,
            yAxis: s.yAxis || undefined,
            categoryField: s.type === 'pie' ? (s.xAxis || undefined) : undefined,
            valueField: s.type === 'pie' ? (s.yAxis || undefined) : undefined,
            valueColumn: s.type === 'kpi' ? (s.yAxis || s.xAxis || undefined) : undefined,
          },
        });

        currentX += defaults.w;
      }

      const queryName = queries.find((q) => q.id === selectedQueryId)?.name || 'AI Report';
      const report = await createReport({
        name: `AI Dashboard — ${queryName}`,
        description: `Auto-generated by AI from query "${queryName}"`,
        layout,
      });

      await fetchReports();
      setMessage({ type: 'success', text: `Report "${report.name}" created! Switching to Report Designer.` });

      // Navigate to Reports tab after a short delay
      setTimeout(() => setActiveTab(3), 1000);
    } catch (err: any) {
      setMessage({ type: 'error', text: err.response?.data?.error || 'Failed to create report' });
    } finally {
      setApplying(false);
    }
  };

  return (
    <Box sx={{ maxWidth: 800 }}>
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 4 }}>
        <AutoAwesomeIcon color="primary" sx={{ fontSize: 32 }} />
        <Box>
          <Typography variant="h4">AI Dashboard Generator</Typography>
          <Typography variant="body2" color="text.secondary">Generate dashboards automatically using AI</Typography>
        </Box>
      </Box>

      {/* AI Config Status */}
      {aiConfig && (
        <Paper variant="outlined" sx={{ p: 1.5, mb: 2, display: 'flex', alignItems: 'center', gap: 1 }}>
          <SettingsIcon fontSize="small" color="action" />
          <Typography variant="body2" color="text.secondary">
            Provider: <strong>{aiConfig.provider}</strong>
            {' · '}Model: <strong>{aiConfig.model}</strong>
            {' · '}
          </Typography>
          <Chip
            label={aiConfig.configured ? 'Configured' : 'Not Configured'}
            size="small"
            color={aiConfig.configured ? 'success' : 'error'}
          />
        </Paper>
      )}

      {/* Query Selector */}
      <Paper sx={{ p: 3, mb: 3 }}>
        <Typography variant="subtitle1" fontWeight="bold" gutterBottom>
          1. Select a saved query
        </Typography>
        <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
          The AI will analyze the query's columns and sample data to suggest an optimal dashboard layout.
        </Typography>

        <FormControl fullWidth sx={{ mb: 2 }}>
          <InputLabel>Query</InputLabel>
          <Select
            value={selectedQueryId}
            label="Query"
            onChange={(e) => {
              setSelectedQueryId(e.target.value as number);
              setSuggestions(null);
              setSampleInfo(null);
            }}
          >
            {queries.map((q) => (
              <MenuItem key={q.id} value={q.id}>
                {q.name} {q.description ? `— ${q.description}` : ''}
              </MenuItem>
            ))}
          </Select>
        </FormControl>

        <Button
          variant="contained"
          startIcon={loading ? <CircularProgress size={18} color="inherit" /> : <AutoAwesomeIcon />}
          onClick={handleGenerate}
          disabled={!selectedQueryId || loading || (aiConfig ? !aiConfig.configured : false)}
          size="large"
        >
          {loading ? 'Analyzing Data...' : 'Generate Dashboard'}
        </Button>
      </Paper>

      {message && (
        <Alert severity={message.type} onClose={() => setMessage(null)} sx={{ mb: 2 }}>
          {message.text}
        </Alert>
      )}

      {/* Suggestions Preview */}
      {suggestions && suggestions.length > 0 && (
        <Paper sx={{ p: 3 }}>
          <Typography variant="subtitle1" fontWeight="bold" gutterBottom>
            2. Review suggested widgets
          </Typography>

          {sampleInfo && (
            <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
              Analyzed {sampleInfo.columns} columns across {sampleInfo.rows} sample rows.
            </Typography>
          )}

          <List>
            {suggestions.map((s, i) => (
              <ListItem key={i} sx={{ bgcolor: '#f9f9f9', borderRadius: 1, mb: 0.5 }}>
                <ListItemIcon>{WIDGET_ICONS[s.type] || <GridOnIcon />}</ListItemIcon>
                <ListItemText
                  primary={s.title}
                  secondary={
                    <Box component="span" sx={{ display: 'flex', gap: 0.5, mt: 0.5, flexWrap: 'wrap' }}>
                      <Chip label={s.type} size="small" variant="outlined" />
                      {s.xAxis && <Chip label={`X: ${s.xAxis}`} size="small" />}
                      {s.yAxis && <Chip label={`Y: ${s.yAxis}`} size="small" />}
                      {s.groupBy && <Chip label={`Group: ${s.groupBy}`} size="small" />}
                    </Box>
                  }
                />
              </ListItem>
            ))}
          </List>

          <Divider sx={{ my: 2 }} />

          <Button
            variant="contained"
            color="success"
            size="large"
            startIcon={applying ? <CircularProgress size={18} color="inherit" /> : <CheckIcon />}
            onClick={handleApplyToCanvas}
            disabled={applying}
          >
            {applying ? 'Creating Report...' : 'Apply to Canvas'}
          </Button>
        </Paper>
      )}
    </Box>
  );
}
